name: Ploomber Cloud

on:
  push:
    branches:
      # only deploy from the main branch
      - main
    paths-ignore:
      # Replace 'path/to/ignored/file.ext' with the path to the file you want to ignore
      - 'pages/sandbox.txt'
jobs:
  deploy-to-ploomber-cloud:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ploomber-cloud

      - name: Deploy
        env:
          PLOOMBER_CLOUD_KEY: ${{ secrets.PLOOMBER_CLOUD_KEY }}
          HUBGIT_TOKEN: ${{ secrets.HUBGIT_TOKEN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TOGETHERAI_API_KEY: ${{ secrets.TOGETHERAI_API_KEY }}
        run: |
          ploomber-cloud deploy --watch-incremental
        # The --watch-incremental flag will print deployment status and deployment
        # log updates to the GitHub logs.
        # To learn more, visit: https://docs.cloud.ploomber.io/en/latest/user-guide/github.html 
